version: '2'
services:
    demoapp-app:
        image: demoapp
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://demoapp-mysql:3306/demoapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://demoapp-elasticsearch:9200
        ports:
            - 8080:8080
    demoapp-mysql:
        extends:
            file: mysql.yml
            service: demoapp-mysql
    demoapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: demoapp-elasticsearch
